name: Esercizio-devops

on: 
  push:
    branches: 
     - main 
     - develop
jobs:
  files-up-to-date:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v5
     - name: Setup node
       uses: actions/setup-node@v6
       with:
         node-version: '20'
     - name: Install pnpm
       run: npm install -g pnpm@latest
     - name: Install dependencies
       run: npm install
     - name: Build
       run: npm run build

     
